# TODO: Remove exposed ports. They are only needed for testing.
version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      xpack.security.enabled: 'false'
  postgres:
    image: apinf-emqttd-postgres
    build:
      context: .
      dockerfile: postgres.Dockerfile
    restart: always
    environment:
      POSTGRES_DB: mqtt
    ports:
      - "5432:5432"
  emqttd:
    image: apinf/emqttd
    restart: always
    environment:
      EMQ_NODE_NAME: "emqttd@localhost"
      EMQ_NODE_COOKIE: "secretcookie"
    depends_on:
      - postgres
      - elasticsearch
    ports:
      - "1883:1883"
