# TODO: Remove exposed ports. They are only needed for testing.
version: '3.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      xpack.security.enabled: 'false'
  postgres:
    image: apinf-emqttd-postgres
    build:
      context: .
      dockerfile: postgres.Dockerfile
    restart: always
    environment:
      POSTGRES_DB: mqtt
    ports:
      - "5432:5432"
  emqttd:
    image: apinf/emqttd
    restart: always
    environment:
      EMQ_NODE_NAME: "emqttd@localhost"
      EMQ_NODE_COOKIE: "secretcookie"
    depends_on:
      - postgres
      - elasticsearch
    ports:
      - "1883:1883"
    volumes:
      - type: bind
        source: ./config
        target: /opt/emqttd/etc
  mqtt_bridge:
    image: apinf/mqtt_bridge:release
    command: "foreground"
    depends_on:
      - emqttd
    volumes:
      - type: bind
        source: ./mqtt_bridge.hsl.conf
        target: /opt/app/releases/0.1.0/mqtt_bridge.conf
